spring:
    application:
        name: EurekaServer

server:
    port: 8761

eureka:
    instance:
        hostname: localhost
#        statusPageUrl: https://${eureka.hostname}/actuator/info
#        healthCheckUrl: https://${eureka.hostname}/actuator/health
#        homePageUrl: https://${eureka.hostname}/
    numberRegistrySyncRetries: 0
    client:
        service-url:
            default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
        # stop trying to register
        register-with-eureka: false
        # stop fetching registy information
        fetch-registry: false
        healthcheck:
            enabled: true